{
   var FullSpecs = [
   
          {
            "Brand": "Arri",
            "Model": "M18 (1200w 1 - SPOT)",
            "Type": "HMI",
            "Style": "Open Face",
            "Color Temp": 6000,
            "Beam Angle": 15,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 27000,
            "Lux @ 5’ ": 27878.76,
            "Spot Diameter @ 5'": 1.32,
            "Lumens": null,
            "Watts": "1200w",
            "Battery plate available?": "no",
            "Dimmable": "50-100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "120-220 VAC",
            "Amps": null,
            "Weight (lb)": 23.1,
            "Width (in)": 15.2,
            "Height (in)": 17.6,
            "Depth (in)": 15.3,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "M18 (1200w 2 - MIDDLE)",
            "Type": "HMI",
            "Style": "Open Face",
            "Color Temp": 6000,
            "Beam Angle": 38,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 6500,
            "Lux @ 5’ ": 69966,
            "Spot Diameter @ 5'": 3.44,
            "Lumens": null,
            "Watts": "1200w",
            "Battery plate available?": "no",
            "Dimmable": "50-100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "120-220 VAC",
            "Amps": null,
            "Weight (lb)": 23.1,
            "Width (in)": 15.2,
            "Height (in)": 17.6,
            "Depth (in)": 15.3,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": " M18 (1200w 3 - FLOOD)",
            "Type": "HMI",
            "Style": "Open Face",
            "Color Temp": 6000,
            "Beam Angle": 62,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 2590,
            "Lux @ 5’ ": 27878.76,
            "Spot Diameter @ 5'": 6,
            "Lumens": null,
            "Watts": "1200w",
            "Battery plate available?": "no",
            "Dimmable": "50-100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "120-220 VAC",
            "Amps": null,
            "Weight (lb)": 23.1,
            "Width (in)": 15.2,
            "Height (in)": 17.6,
            "Depth (in)": 15.3,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "M18 (1800w 1 - SPOT)",
            "Type": "HMI",
            "Style": "Open Face",
            "Color Temp": 6000,
            "Beam Angle": 16,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 39200,
            "Lux @ 5’ ": 421948.8,
            "Spot Diameter @ 5'": 1.4,
            "Lumens": null,
            "Watts": "1800w",
            "Battery plate available?": "no",
            "Dimmable": "50-100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "120-220 VAC",
            "Amps": 20,
            "Weight (lb)": 23.1,
            "Width (in)": 15.2,
            "Height (in)": 17.6,
            "Depth (in)": 15.3,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "M18 (1800w 2 - MIDDLE)",
            "Type": "HMI",
            "Style": "Open Face",
            "Color Temp": 6000,
            "Beam Angle": 39,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 8660,
            "Lux @ 5’ ": 93216.23999999999,
            "Spot Diameter @ 5'": 3.5,
            "Lumens": null,
            "Watts": "1800w",
            "Battery plate available?": "no",
            "Dimmable": "50-100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "120-220 VAC",
            "Amps": 20,
            "Weight (lb)": 23.1,
            "Width (in)": 15.2,
            "Height (in)": 17.6,
            "Depth (in)": 15.3,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "M18 (1800w 3 - FLOOD)",
            "Type": "HMI",
            "Style": "Open Face",
            "Color Temp": 6000,
            "Beam Angle": 63,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 3440,
            "Lux @ 5’ ": 37028.159999999996,
            "Spot Diameter @ 5'": 6,
            "Lumens": null,
            "Watts": "1800w",
            "Battery plate available?": "no",
            "Dimmable": "50-100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "120-220 VAC",
            "Amps": 20,
            "Weight (lb)": 23.1,
            "Width (in)": 15.2,
            "Height (in)": 17.6,
            "Depth (in)": 15.3,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "Skypanel S120-C",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": 106,
            "FC @ 5’ (Tungsten)        .": 488,
            "Lux @ 5’ (Tungsten)": 5252.831999999999,
            "FC @ 5’ (Daylight)": 448,
            "Lux @ 5’ ": 4822.272,
            "Spot Diameter @ 5'": 13.27,
            "Lumens": null,
            "Watts": "400w",
            "Battery plate available?": "3 pin xlr",
            "Dimmable": "Dimmable",
            "CRI": "94+",
            "TLCI": "94+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": 35.3,
            "Width (in)": 57.8,
            "Height (in)": 18.6,
            "Depth (in)": 5.2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX / Ethernet",
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "Skypanel S30-C",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": 106,
            "FC @ 5’ (Tungsten)        .": 221,
            "Lux @ 5’ (Tungsten)": 2378.844,
            "FC @ 5’ (Daylight)": 216,
            "Lux @ 5’ ": 2325.024,
            "Spot Diameter @ 5'": 13.27,
            "Lumens": null,
            "Watts": "200w",
            "Battery plate available?": "3 pin xlr",
            "Dimmable": "Dimmable",
            "CRI": "95+",
            "TLCI": "95+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": 16.3,
            "Width (in)": 22,
            "Height (in)": 20,
            "Depth (in)": 5.2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX / Ethernet",
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "Skypanel S360-C",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": 103,
            "FC @ 5’ (Tungsten)        .": 2028,
            "Lux @ 5’ (Tungsten)": 21829.392,
            "FC @ 5’ (Daylight)": 1848,
            "Lux @ 5’ ": 19891.872,
            "Spot Diameter @ 5'": 12.57,
            "Lumens": null,
            "Watts": "1500w",
            "Battery plate available?": "3 pin xlr",
            "Dimmable": "Dimmable",
            "CRI": "95+",
            "TLCI": "95+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": 90.4,
            "Width (in)": 62.8,
            "Height (in)": 43.5,
            "Depth (in)": 8,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX / Ethernet",
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Arri",
            "Model": "Skypanel S60-C",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": 106,
            "FC @ 5’ (Tungsten)        .": 453,
            "Lux @ 5’ (Tungsten)": 4876.092,
            "FC @ 5’ (Daylight)": 444,
            "Lux @ 5’ ": 4779.215999999999,
            "Spot Diameter @ 5'": 13.27,
            "Lumens": null,
            "Watts": "420w",
            "Battery plate available?": "3 pin xlr",
            "Dimmable": "Dimmable",
            "CRI": "95+",
            "TLCI": "95+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": 25.8,
            "Width (in)": 32,
            "Height (in)": 17,
            "Depth (in)": 5.2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX / Ethernet",
            "Notes": null,
            "Data Reference": "Arri Photometrics App"
          },
          {
            "Brand": "Astera",
            "Model": "Pixel Tube",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "RGBW",
            "Beam Angle": 180,
            "FC @ 5’ (Tungsten)        .": 10.497956150130063,
            "Lux @ 5’ (Tungsten)": 113,
            "FC @ 5’ (Daylight)": 10.405053883314753,
            "Lux @ 5’ ": 112,
            "Spot Diameter @ 5'": 14.6,
            "Lumens": null,
            "Watts": 28,
            "Battery plate available?": "int (wh unpublished)",
            "Dimmable": "Dimmable",
            "CRI": 88,
            "TLCI": null,
            "Voltage": "90-264",
            "Amps": null,
            "Weight (lb)": 2.2,
            "Width (in)": 40.7,
            "Height (in)": 1.6,
            "Depth (in)": 1.6,
            "Flicker Free?": null,
            "Ballast / Dimmer": "integrated",
            "Remote Control": "WxDMX / WiFi",
            "Notes": null,
            "Data Reference": "http://astera-led.com/ax1/ & a brochure they emailed me"
          },
          {
            "Brand": "Astera",
            "Model": "Titan Tube",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "RGBW",
            "Beam Angle": 125,
            "FC @ 5’ (Tungsten)        .": 31.83973429951691,
            "Lux @ 5’ (Tungsten)": 342.7229,
            "FC @ 5’ (Daylight)": 31.83973429951691,
            "Lux @ 5’ ": 342.7229,
            "Spot Diameter @ 5'": 14.6,
            "Lumens": null,
            "Watts": "48w",
            "Battery plate available?": "int (wh unpublished)",
            "Dimmable": "Dimmable",
            "CRI": "95+",
            "TLCI": 97,
            "Voltage": "90-264",
            "Amps": null,
            "Weight (lb)": 3,
            "Width (in)": 40.7,
            "Height (in)": 1.6,
            "Depth (in)": 1.6,
            "Flicker Free?": null,
            "Ballast / Dimmer": "integrated",
            "Remote Control": "WxDMX / WiFi",
            "Notes": null,
            "Data Reference": "http://astera-led.com/titan/ & a brochure they emailed me"
          },
          {
            "Brand": "Digital Sputnik",
            "Model": " DS1",
            "Type": "LED",
            "Style": "Beam",
            "Color Temp": "RGBW",
            "Beam Angle": 20,
            "FC @ 5’ (Tungsten)        .": 1336,
            "Lux @ 5’ (Tungsten)": 14380.704,
            "FC @ 5’ (Daylight)": 1336,
            "Lux @ 5’ ": 14380.704,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "140w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-260",
            "Amps": null,
            "Weight (lb)": 2.8,
            "Width (in)": 4,
            "Height (in)": 4,
            "Depth (in)": null,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Removable",
            "Remote Control": "WiFi / WxDMX avail",
            "Notes": null,
            "Data Reference": "https://www.digitalsputnik.com/product/ds1-set/\nhttps://www.bhphotovideo.com/c/product/1257171-REG/digital_sputnik_ds5a_ds_1_led_modular_light.html"
          },
          {
            "Brand": "Digital Sputnik",
            "Model": " DS3",
            "Type": "LED",
            "Style": "Beam",
            "Color Temp": "RGBW",
            "Beam Angle": 20,
            "FC @ 5’ (Tungsten)        .": 4008,
            "Lux @ 5’ (Tungsten)": 43142.112,
            "FC @ 5’ (Daylight)": 4008,
            "Lux @ 5’ ": 43142.112,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "420w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-260",
            "Amps": null,
            "Weight (lb)": 26.5,
            "Width (in)": 16.5,
            "Height (in)": 15.7,
            "Depth (in)": 9.1,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Removable",
            "Remote Control": "WiFi / WxDMX avail",
            "Notes": null,
            "Data Reference": "https://www.bhphotovideo.com/c/product/1257169-REG/digital_sputnik_ds1f_ds_3_led_modular_light.html"
          },
          {
            "Brand": "Digital Sputnik",
            "Model": " DS6",
            "Type": "LED",
            "Style": "Beam",
            "Color Temp": "RGBW",
            "Beam Angle": 20,
            "FC @ 5’ (Tungsten)        .": 8016,
            "Lux @ 5’ (Tungsten)": 86284.224,
            "FC @ 5’ (Daylight)": 8016,
            "Lux @ 5’ ": 86284.224,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "840w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-260",
            "Amps": null,
            "Weight (lb)": 97,
            "Width (in)": 24.8,
            "Height (in)": 45.3,
            "Depth (in)": 10.6,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Removable",
            "Remote Control": "WiFi / WxDMX avail",
            "Notes": null,
            "Data Reference": "https://www.bhphotovideo.com/c/product/1257168-REG/digital_sputnik_ds2b_ds_6_led_modular_light.html"
          },
          {
            "Brand": "Digital Sputnik",
            "Model": " Voyager 2'",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "RGBW",
            "Beam Angle": 270,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": 0,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": 0,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "20w",
            "Battery plate available?": "int (45wh)",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": 2.4,
            "Width (in)": 24,
            "Height (in)": 2.5,
            "Depth (in)": 2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": null,
            "Remote Control": "mobile app / WxDMX",
            "Notes": "The fixture can be used fully submerged up to 2 meters of depth for short time periods (30min). The 2-meter maximum is to keep the manufacturing cost and weight of the unit reasonable. \n\nColor can be animated\n\nWe will provide a BTO option for an extra 150USD/2ft- 200USD/4ft per fixture to enhance the operational depth to 10 meters. These units will ship with wired control for fixed large-scale installations.",
            "Data Reference": "http://www.4kshooters.net/wp-content/uploads/2017/07/Screen-Shot-2017-07-13-at-18.34.24-e1499967468607.jpg"
          },
          {
            "Brand": "Digital Sputnik",
            "Model": " Voyager 4'",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "RGBW",
            "Beam Angle": 270,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": 0,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": 0,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "40w",
            "Battery plate available?": "int (90wh)",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": 4.9,
            "Width (in)": 44,
            "Height (in)": 2.5,
            "Depth (in)": 2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": null,
            "Remote Control": "mobile app / WxDMX",
            "Notes": "The fixture can be used fully submerged up to 2 meters of depth for short time periods (30min). The 2-meter maximum is to keep the manufacturing cost and weight of the unit reasonable. \n\nColor can be animated\n\nWe will provide a BTO option for an extra 150USD/2ft- 200USD/4ft per fixture to enhance the operational depth to 10 meters. These units will ship with wired control for fixed large-scale installations.",
            "Data Reference": "http://www.4kshooters.net/wp-content/uploads/2017/07/Screen-Shot-2017-07-13-at-18.34.24-e1499967468607.jpg"
          },
          {
            "Brand": "DMG Lumiere ",
            "Model": "maxiswitch",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "3000-5600",
            "Beam Angle": "Variable (2 lights hinged)",
            "FC @ 5’ (Tungsten)        .": 620,
            "Lux @ 5’ (Tungsten)": 6673.679999999999,
            "FC @ 5’ (Daylight)": 672,
            "Lux @ 5’ ": 7233.407999999999,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "520w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-242",
            "Amps": null,
            "Weight (lb)": 27,
            "Width (in)": 48,
            "Height (in)": 30,
            "Depth (in)": 0.75,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "Wifi / WxDMX / Ethernet",
            "Notes": null,
            "Data Reference": "http://www.dmglumiere.com/download/20.pdf"
          },
          {
            "Brand": "DMG Lumiere ",
            "Model": "miniswitch",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "3000-5600",
            "Beam Angle": 45,
            "FC @ 5’ (Tungsten)        .": 88,
            "Lux @ 5’ (Tungsten)": 947.232,
            "FC @ 5’ (Daylight)": 84,
            "Lux @ 5’ ": 904.1759999999999,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "85w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-241",
            "Amps": null,
            "Weight (lb)": 3.7,
            "Width (in)": 23,
            "Height (in)": 7.8,
            "Depth (in)": 0.8,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX avail",
            "Notes": null,
            "Data Reference": "http://www.dmglumiere.com/download/21.pdf"
          },
          {
            "Brand": "DMG Lumiere ",
            "Model": "SL1 Switch",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "3000-5600",
            "Beam Angle": 45,
            "FC @ 5’ (Tungsten)        .": 184,
            "Lux @ 5’ (Tungsten)": 1980.5759999999998,
            "FC @ 5’ (Daylight)": 176,
            "Lux @ 5’ ": 1894.464,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "170w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": null,
            "Weight (lb)": 7.5,
            "Width (in)": 44.4,
            "Height (in)": 7.8,
            "Depth (in)": 0.75,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX avail",
            "Notes": null,
            "Data Reference": "http://www.dmglumiere.com/download/12.pdf"
          },
          {
            "Brand": "ETC",
            "Model": " Source 4 Junior Zoom(Minimum)",
            "Type": "Tungsten",
            "Style": "Ellipsoidal",
            "Color Temp": 3250,
            "Beam Angle": "21-40",
            "FC @ 5’ (Tungsten)        .": 859,
            "Lux @ 5’ (Tungsten)": 9257,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 1.9,
            "Lumens": null,
            "Watts": "575w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "115-240",
            "Amps": null,
            "Weight (lb)": 10,
            "Width (in)": 19.3,
            "Height (in)": 18.5,
            "Depth (in)": 9.7,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737459979"
          },
          {
            "Brand": "ETC",
            "Model": " Source 4 Junior Zoom(Maximum)",
            "Type": "Tungsten",
            "Style": "Ellipsoidal",
            "Color Temp": 3250,
            "Beam Angle": "21-40",
            "FC @ 5’ (Tungsten)        .": 3087,
            "Lux @ 5’ (Tungsten)": 33192,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 3.64,
            "Lumens": null,
            "Watts": "575w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "115-240",
            "Amps": null,
            "Weight (lb)": 10,
            "Width (in)": 19.3,
            "Height (in)": 18.5,
            "Depth (in)": 9.7,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737459979"
          },
          {
            "Brand": "ETC",
            "Model": "Source 4 Zoom 15-30 (Minimum)",
            "Type": "Tungsten",
            "Style": "Ellipsoidal",
            "Color Temp": 3250,
            "Beam Angle": 43790,
            "FC @ 5’ (Tungsten)        .": 4230,
            "Lux @ 5’ (Tungsten)": 45504,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 1.9,
            "Lumens": null,
            "Watts": "750w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "115-240",
            "Amps": null,
            "Weight (lb)": 21,
            "Width (in)": 29.2,
            "Height (in)": 21.1,
            "Depth (in)": 9.2,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460417"
          },
          {
            "Brand": "ETC",
            "Model": "Source 4 Zoom 15-30(Maximum)",
            "Type": "Tungsten",
            "Style": "Ellipsoidal",
            "Color Temp": 3250,
            "Beam Angle": 43790,
            "FC @ 5’ (Tungsten)        .": 15840,
            "Lux @ 5’ (Tungsten)": 170316,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 0.9,
            "Lumens": null,
            "Watts": "750w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "115-240",
            "Amps": null,
            "Weight (lb)": 21,
            "Width (in)": 29.2,
            "Height (in)": 21.1,
            "Depth (in)": 9.2,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460417"
          },
          {
            "Brand": "ETC",
            "Model": "Source 4 Zoom 25-50(Minimum)",
            "Type": "Tungsten",
            "Style": "Ellipsoidal",
            "Color Temp": 3250,
            "Beam Angle": "21-29",
            "FC @ 5’ (Tungsten)        .": 2540,
            "Lux @ 5’ (Tungsten)": 27332,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 1.9,
            "Lumens": null,
            "Watts": "750w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "115-240",
            "Amps": null,
            "Weight (lb)": 17,
            "Width (in)": 23.9,
            "Height (in)": 21.3,
            "Depth (in)": 8.4,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460396"
          },
          {
            "Brand": "ETC",
            "Model": "Source 4 Zoom 25-50(Maximum)",
            "Type": "Tungsten",
            "Style": "Ellipsoidal",
            "Color Temp": 3250,
            "Beam Angle": "21-29",
            "FC @ 5’ (Tungsten)        .": 6030,
            "Lux @ 5’ (Tungsten)": 64908,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 2.6,
            "Lumens": null,
            "Watts": "750w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "115-240",
            "Amps": null,
            "Weight (lb)": 17,
            "Width (in)": 23.9,
            "Height (in)": 21.3,
            "Depth (in)": 8.4,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460396"
          },
          {
            "Brand": "K5600",
            "Model": " Jokerbug 400 (1 - SPOT)",
            "Type": "HMI",
            "Style": "PAR",
            "Color Temp": 5600,
            "Beam Angle": 3,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 61760,
            "Lux @ 5’ ": 664784.64,
            "Spot Diameter @ 5'": 0.25,
            "Lumens": null,
            "Watts": "400w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": null,
            "TLCI": null,
            "Voltage": "90-132 or 180-265",
            "Amps": 5.5,
            "Weight (lb)": 4.5,
            "Width (in)": 10.5,
            "Height (in)": 7.75,
            "Depth (in)": 7.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.k5600.com/products/jb400/jb400.pdf"
          },
          {
            "Brand": "K5600",
            "Model": "Jokerbug 400 (4 - SUPER WIDE)",
            "Type": "HMI",
            "Style": "PAR",
            "Color Temp": 5600,
            "Beam Angle": 58,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 752,
            "Lux @ 5’ ": 8094.527999999999,
            "Spot Diameter @ 5'": 5.5,
            "Lumens": null,
            "Watts": "400w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": null,
            "TLCI": null,
            "Voltage": "90-132 or 180-265",
            "Amps": 5.5,
            "Weight (lb)": 4.5,
            "Width (in)": 10.5,
            "Height (in)": 7.75,
            "Depth (in)": 7.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.k5600.com/products/jb400/jb400.pdf"
          },
          {
            "Brand": "K5600",
            "Model": " Jokerbug 400 (5 - FRESNEL FROST)",
            "Type": "HMI",
            "Style": "PAR",
            "Color Temp": 5600,
            "Beam Angle": 44,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 576,
            "Lux @ 5’ ": 6200.063999999999,
            "Spot Diameter @ 5'": 4,
            "Lumens": null,
            "Watts": "400w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": null,
            "TLCI": null,
            "Voltage": "90-132 or 180-265",
            "Amps": 5.5,
            "Weight (lb)": 4.5,
            "Width (in)": 10.5,
            "Height (in)": 7.75,
            "Depth (in)": 7.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.k5600.com/products/jb400/jb400.pdf"
          },
          {
            "Brand": "K5600",
            "Model": "Jokerbug 800 (1 - SPOT)",
            "Type": "HMI",
            "Style": "PAR",
            "Color Temp": 5600,
            "Beam Angle": 4,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 83760,
            "Lux @ 5’ ": 901592.6399999999,
            "Spot Diameter @ 5'": 0.4,
            "Lumens": null,
            "Watts": "800w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": null,
            "TLCI": null,
            "Voltage": "90-132 or 180-265",
            "Amps": 12.5,
            "Weight (lb)": 6,
            "Width (in)": 13,
            "Height (in)": 9,
            "Depth (in)": 9,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.k5600.com/products/jb800/jb800.pdf"
          },
          {
            "Brand": "K5600",
            "Model": "Jokerbug 800 (4 - SUPER WIDE)",
            "Type": "HMI",
            "Style": "PAR",
            "Color Temp": 5600,
            "Beam Angle": 44,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 2628,
            "Lux @ 5’ ": 28287.791999999998,
            "Spot Diameter @ 5'": 4,
            "Lumens": null,
            "Watts": "800w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": null,
            "TLCI": null,
            "Voltage": "90-132 or 180-265",
            "Amps": 12.5,
            "Weight (lb)": 6,
            "Width (in)": 13,
            "Height (in)": 9,
            "Depth (in)": 9,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.k5600.com/products/jb800/jb800.pdf"
          },
          {
            "Brand": "K5600",
            "Model": "Jokerbug 800 (5 - FRESNEL FROST)",
            "Type": "HMI",
            "Style": "PAR",
            "Color Temp": 5600,
            "Beam Angle": 37,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 1552,
            "Lux @ 5’ ": 16705.728,
            "Spot Diameter @ 5'": 3.4,
            "Lumens": null,
            "Watts": "800w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": null,
            "TLCI": null,
            "Voltage": "90-132 or 180-265",
            "Amps": 12.5,
            "Weight (lb)": 6,
            "Width (in)": 13,
            "Height (in)": 9,
            "Depth (in)": 9,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.k5600.com/products/jb800/jb800.pdf"
          },
          {
            "Brand": "KinoFlo",
            "Model": "2' 4-Bank",
            "Type": "Fluorescent",
            "Style": "Array",
            "Color Temp": "2900 3200 5500",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 44,
            "Lux @ 5’ (Tungsten)": 473.616,
            "FC @ 5’ (Daylight)": 44,
            "Lux @ 5’ ": 473.616,
            "Spot Diameter @ 5'": null,
            "Lumens": 6560,
            "Watts": "160w",
            "Battery plate available?": "no",
            "Dimmable": "no",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 1.4,
            "Weight (lb)": 7.5,
            "Width (in)": 27,
            "Height (in)": 13,
            "Depth (in)": 2.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX avail",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/Fixtures%20Remote/Select_DMX_4Bank/4Bank_DMX.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": " 4' 4-Bank",
            "Type": "Fluorescent",
            "Style": "Array",
            "Color Temp": "2900 3200 5500",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 128,
            "Lux @ 5’ (Tungsten)": 1377.792,
            "FC @ 5’ (Daylight)": 128,
            "Lux @ 5’ ": 1377.792,
            "Spot Diameter @ 5'": null,
            "Lumens": 13400,
            "Watts": "300w",
            "Battery plate available?": "no",
            "Dimmable": "~28% or 100%",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 2.6,
            "Weight (lb)": 11.5,
            "Width (in)": 52,
            "Height (in)": 13,
            "Depth (in)": 3.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX avail",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/Fixtures%20Remote/Select_DMX_4Bank/4Bank_DMX.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": "Celeb 450",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 236,
            "Lux @ 5’ (Tungsten)": 2540.3039999999996,
            "FC @ 5’ (Daylight)": 236,
            "Lux @ 5’ ": 2540.3039999999996,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "255w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 2.5,
            "Weight (lb)": 26,
            "Width (in)": 45,
            "Height (in)": 14,
            "Depth (in)": 5,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "DMX / WxDMX",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/LED/Celeb%20450%20DMX/Celeb_450_DMX.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": "Celeb 850",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 444,
            "Lux @ 5’ (Tungsten)": 4779.215999999999,
            "FC @ 5’ (Daylight)": 444,
            "Lux @ 5’ ": 4779.215999999999,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "575w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 5,
            "Weight (lb)": 40,
            "Width (in)": 45,
            "Height (in)": 25,
            "Depth (in)": 6,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "DMX / WxDMX",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/LED/Celeb%20850/Celeb_850.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": "Diva-Lite 20",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 104,
            "Lux @ 5’ (Tungsten)": 1119.456,
            "FC @ 5’ (Daylight)": 104,
            "Lux @ 5’ ": 1119.456,
            "Spot Diameter @ 5'": null,
            "Lumens": 7766,
            "Watts": "123w",
            "Battery plate available?": "proprietary / 3pin xlr",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 1.3,
            "Weight (lb)": 14.5,
            "Width (in)": 25,
            "Height (in)": 13,
            "Depth (in)": 6,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "DMX / WxDMX",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/LED/Diva_Lite_LED/Diva_Lite_LED_30_20.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": "Diva-Lite 30",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 112,
            "Lux @ 5’ (Tungsten)": 1205.568,
            "FC @ 5’ (Daylight)": 112,
            "Lux @ 5’ ": 1205.568,
            "Spot Diameter @ 5'": null,
            "Lumens": 8256,
            "Watts": "129w",
            "Battery plate available?": "proprietary / 3pin xlr",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 1.3,
            "Weight (lb)": 17,
            "Width (in)": 39,
            "Height (in)": 10.5,
            "Depth (in)": 6,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "DMX / WxDMX",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/LED/Diva_Lite_LED/Diva_Lite_LED_30_20.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": "Select 20 / Freestyle 21",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 104,
            "Lux @ 5’ (Tungsten)": 1119.456,
            "FC @ 5’ (Daylight)": 104,
            "Lux @ 5’ ": 1119.456,
            "Spot Diameter @ 5'": null,
            "Lumens": 7766,
            "Watts": "123w",
            "Battery plate available?": "proprietary / 3pin xlr",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 1.3,
            "Weight (lb)": 11.5,
            "Width (in)": 26.5,
            "Height (in)": 13,
            "Depth (in)": 3.5,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX / WxDMX",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/LED/FreeStyle/Photometrics.html"
          },
          {
            "Brand": "KinoFlo",
            "Model": "Select 30 / Freestyle 31",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": 112,
            "Lux @ 5’ (Tungsten)": 1205.568,
            "FC @ 5’ (Daylight)": 112,
            "Lux @ 5’ ": 1205.568,
            "Spot Diameter @ 5'": null,
            "Lumens": 8256,
            "Watts": "130w",
            "Battery plate available?": "proprietary / 3pin xlr",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "100-240",
            "Amps": 1.3,
            "Weight (lb)": 15,
            "Width (in)": 40.5,
            "Height (in)": 10.5,
            "Depth (in)": 3.5,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX / WxDMX",
            "Notes": null,
            "Data Reference": "https://www.kinoflo.com/Products%20Button/LED/FreeStyle/Photometrics.html"
          },
          {
            "Brand": "Litemat+",
            "Model": "2L",
            "Type": "LED",
            "Style": "Panel",
            "Color Temp": "2600-6200",
            "Beam Angle": 112,
            "FC @ 5’ (Tungsten)        .": 163,
            "Lux @ 5’ (Tungsten)": 1754.532,
            "FC @ 5’ (Daylight)": 163,
            "Lux @ 5’ ": 1754.532,
            "Spot Diameter @ 5'": 14.8,
            "Lumens": 5096,
            "Watts": "100w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": "95+",
            "TLCI": "95+",
            "Voltage": "100-240",
            "Amps": 4.17,
            "Weight (lb)": 3.8,
            "Width (in)": 40,
            "Height (in)": 11.5,
            "Depth (in)": 0.9,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.litegear.com/wp-content/uploads/2017/09/LiteMat-Plus-Catalog.pdf"
          },
          {
            "Brand": "Litemat+",
            "Model": 3,
            "Type": "LED",
            "Style": "Panel",
            "Color Temp": "2600-6200",
            "Beam Angle": 112,
            "FC @ 5’ (Tungsten)        .": 213,
            "Lux @ 5’ (Tungsten)": 2292.732,
            "FC @ 5’ (Daylight)": 213,
            "Lux @ 5’ ": 2292.732,
            "Spot Diameter @ 5'": 14.8,
            "Lumens": 7644,
            "Watts": "150w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": "95+",
            "TLCI": "95+",
            "Voltage": "100-240",
            "Amps": 6.25,
            "Weight (lb)": 4.8,
            "Width (in)": 30.5,
            "Height (in)": 21,
            "Depth (in)": 0.9,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://www.litegear.com/wp-content/uploads/2017/09/LiteMat-Plus-Catalog.pdf"
          },
          {
            "Brand": "Litepanels",
            "Model": " Astra 3x Bi-Color",
            "Type": "LED",
            "Style": "Panel",
            "Color Temp": "3200-5600",
            "Beam Angle": 46,
            "FC @ 5’ (Tungsten)        .": 301,
            "Lux @ 5’ (Tungsten)": 3239.964,
            "FC @ 5’ (Daylight)": 345,
            "Lux @ 5’ ": 3713.58,
            "Spot Diameter @ 5'": 4.25,
            "Lumens": null,
            "Watts": "55w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": "95/D 98/T",
            "TLCI": "95/D 98/T",
            "Voltage": "100-240",
            "Amps": null,
            "Weight (lb)": 7,
            "Width (in)": 17.7,
            "Height (in)": 16.3,
            "Depth (in)": 5.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "BT & DMX avail ",
            "Notes": null,
            "Data Reference": "http://www.litepanels.com/dam/jcr:10ec610a-44bc-417d-bb4e-4c4a401640ec/Litepanels-ASTRA-Brochure-2017.pdf"
          },
          {
            "Brand": "Litepanels",
            "Model": " Astra 6x Bi-Color",
            "Type": "LED",
            "Style": "Panel",
            "Color Temp": "3200-5600",
            "Beam Angle": 46,
            "FC @ 5’ (Tungsten)        .": 528,
            "Lux @ 5’ (Tungsten)": 5683.392,
            "FC @ 5’ (Daylight)": 588,
            "Lux @ 5’ ": 6329.232,
            "Spot Diameter @ 5'": 4.25,
            "Lumens": null,
            "Watts": "105w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": "95/D 98/T",
            "TLCI": "95/D 98/T",
            "Voltage": "100-240",
            "Amps": null,
            "Weight (lb)": 7,
            "Width (in)": 17.7,
            "Height (in)": 16.3,
            "Depth (in)": 5.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "BT & DMX avail ",
            "Notes": null,
            "Data Reference": "http://www.litepanels.com/dam/jcr:10ec610a-44bc-417d-bb4e-4c4a401640ec/Litepanels-ASTRA-Brochure-2017.pdf"
          },
          {
            "Brand": "Litepanels",
            "Model": " Astra Soft",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "3200-5600",
            "Beam Angle": 96,
            "FC @ 5’ (Tungsten)        .": 95,
            "Lux @ 5’ (Tungsten)": 1022.5799999999999,
            "FC @ 5’ (Daylight)": 109,
            "Lux @ 5’ ": 1173.2759999999998,
            "Spot Diameter @ 5'": 11.1,
            "Lumens": null,
            "Watts": "105w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": "95/D 98/T",
            "TLCI": "95/D 98/T",
            "Voltage": "100-240",
            "Amps": null,
            "Weight (lb)": 7,
            "Width (in)": 17.7,
            "Height (in)": 16.3,
            "Depth (in)": 5.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "BT & DMX avail ",
            "Notes": null,
            "Data Reference": "http://www.litepanels.com/dam/jcr:10ec610a-44bc-417d-bb4e-4c4a401640ec/Litepanels-ASTRA-Brochure-2017.pdf"
          },
          {
            "Brand": "Litepanels",
            "Model": "Gemini",
            "Type": "LED",
            "Style": "Soft Panel",
            "Color Temp": "RGBW",
            "Beam Angle": 93,
            "FC @ 5’ (Tungsten)        .": 389,
            "Lux @ 5’ (Tungsten)": 4187.196,
            "FC @ 5’ (Daylight)": 389,
            "Lux @ 5’ ": 4187.196,
            "Spot Diameter @ 5'": 10.5,
            "Lumens": null,
            "Watts": "350w",
            "Battery plate available?": "3 pin xlr",
            "Dimmable": "Dimmable",
            "CRI": "97/D 99/T",
            "TLCI": "97/D 99/T",
            "Voltage": "100-240",
            "Amps": null,
            "Weight (lb)": 22.2,
            "Width (in)": 25,
            "Height (in)": 12.5,
            "Depth (in)": 6.5,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "BT & DMX incl",
            "Notes": null,
            "Data Reference": "https://www.videodata.de/shop/media/products/Litepanels_Gemini_Datenblatt.pdf"
          },
          {
            "Brand": "Mole",
            "Model": " Baby 1k(Minimum)",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "15-58",
            "FC @ 5’ (Tungsten)        .": 700,
            "Lux @ 5’ (Tungsten)": 7535,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 4.3,
            "Lumens": null,
            "Watts": "1000w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 8.3,
            "Weight (lb)": 13.75,
            "Width (in)": 11.25,
            "Height (in)": 10.5,
            "Depth (in)": 8.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/407.pdf"
          },
          {
            "Brand": "Mole",
            "Model": " Baby 1k(Maximum)",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "15-58",
            "FC @ 5’ (Tungsten)        .": 6320,
            "Lux @ 5’ (Tungsten)": 68028,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 0.8,
            "Lumens": null,
            "Watts": "1000w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 8.3,
            "Weight (lb)": 13.75,
            "Width (in)": 11.25,
            "Height (in)": 10.5,
            "Depth (in)": 8.5,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/407.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Baby 200w Bi-Color LED(Minimum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": "2700-6500",
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 1300,
            "Lux @ 5’ (Tungsten)": 19375,
            "FC @ 5’ (Daylight)": 460,
            "Lux @ 5’ ": 7320,
            "Spot Diameter @ 5'": 0.9,
            "Lumens": null,
            "Watts": "200w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 2,
            "Weight (lb)": 13,
            "Width (in)": 12.4,
            "Height (in)": 11.2,
            "Depth (in)": 10,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX- WxDMX- BT",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Baby 200w Bi-Color LED(Maximum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": "2700-6500",
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 1300,
            "Lux @ 5’ (Tungsten)": 19375,
            "FC @ 5’ (Daylight)": 1800,
            "Lux @ 5’ ": 20452,
            "Spot Diameter @ 5'": 0.9,
            "Lumens": null,
            "Watts": "200w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 2,
            "Weight (lb)": 13,
            "Width (in)": 12.4,
            "Height (in)": 11.2,
            "Depth (in)": 10,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX- WxDMX- BT",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": " Junior 2k(Minimum)",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "27-55",
            "FC @ 5’ (Tungsten)        .": 1600,
            "Lux @ 5’ (Tungsten)": 17222,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 4.25,
            "Lumens": null,
            "Watts": "2000w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 16.7,
            "Weight (lb)": 16.5,
            "Width (in)": 11.75,
            "Height (in)": 13.25,
            "Depth (in)": 9.75,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/4131.pdf"
          },
          {
            "Brand": "Mole",
            "Model": " Junior 2k(Maximum)",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "27-55",
            "FC @ 5’ (Tungsten)        .": 6000,
            "Lux @ 5’ (Tungsten)": 64585,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 1.4,
            "Lumens": null,
            "Watts": "2000w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 16.7,
            "Weight (lb)": 16.5,
            "Width (in)": 11.75,
            "Height (in)": 13.25,
            "Depth (in)": 9.75,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/4131.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Junior 300w Bi-Color LED (Minimum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": "2700-6500",
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 620,
            "Lux @ 5’ (Tungsten)": 6674,
            "FC @ 5’ (Daylight)": 680,
            "Lux @ 5’ ": 20452,
            "Spot Diameter @ 5'": 1.1,
            "Lumens": null,
            "Watts": "300w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 3,
            "Weight (lb)": 17,
            "Width (in)": 12.6,
            "Height (in)": 13.6,
            "Depth (in)": 14,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX- WxDMX- BT",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Junior 300w Bi-Color LED (Maximum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": "2700-6500",
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 1800,
            "Lux @ 5’ (Tungsten)": 19375,
            "FC @ 5’ (Daylight)": 1900,
            "Lux @ 5’ ": 7320,
            "Spot Diameter @ 5'": 1.1,
            "Lumens": null,
            "Watts": "300w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 3,
            "Weight (lb)": 17,
            "Width (in)": 12.6,
            "Height (in)": 13.6,
            "Depth (in)": 14,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX- WxDMX- BT",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Midget 200w(Minimum)",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "12-58",
            "FC @ 5’ (Tungsten)        .": 110,
            "Lux @ 5’ (Tungsten)": 1184,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 4.3,
            "Lumens": null,
            "Watts": "200w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 1.7,
            "Weight (lb)": 4.75,
            "Width (in)": 6.25,
            "Height (in)": 6.12,
            "Depth (in)": 4,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/2351.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Midget 200w(Maximum)",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "12-58",
            "FC @ 5’ (Tungsten)        .": 1060,
            "Lux @ 5’ (Tungsten)": 11410,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 0.6,
            "Lumens": null,
            "Watts": "200w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 1.7,
            "Weight (lb)": 4.75,
            "Width (in)": 6.25,
            "Height (in)": 6.12,
            "Depth (in)": 4,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/2351.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Senior 5k",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "17-61",
            "FC @ 5’ (Tungsten)        .": 3800,
            "Lux @ 5’ (Tungsten)": 40903,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 4.7,
            "Lumens": null,
            "Watts": "5000w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 41.6,
            "Weight (lb)": 33.75,
            "Width (in)": 17.25,
            "Height (in)": 14,
            "Depth (in)": 16,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/4191.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Senior 5k",
            "Type": "Tungsten",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "17-61",
            "FC @ 5’ (Tungsten)        .": 23200,
            "Lux @ 5’ (Tungsten)": 249725,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": 0.9,
            "Lumens": null,
            "Watts": "5000w",
            "Battery plate available?": "no",
            "Dimmable": "req dimmer",
            "CRI": null,
            "TLCI": null,
            "Voltage": "120-240",
            "Amps": 41.6,
            "Weight (lb)": 33.75,
            "Width (in)": 17.25,
            "Height (in)": 14,
            "Depth (in)": 16,
            "Flicker Free?": "no",
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/data/4191.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Senior 900w LED (Daylight)(Minimum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": 5600,
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 4000,
            "Lux @ 5’ ": 43056,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "900w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 8,
            "Weight (lb)": 41,
            "Width (in)": 20.7,
            "Height (in)": 24.6,
            "Depth (in)": 17.4,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Senior 900w LED (Daylight)(Maximum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": 5600,
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 8000,
            "Lux @ 5’ ": 86112,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "900w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 8,
            "Weight (lb)": 41,
            "Width (in)": 20.7,
            "Height (in)": 24.6,
            "Depth (in)": 17.4,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Senior 900w LED (Tungsten)(Minimum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 3200,
            "Lux @ 5’ (Tungsten)": 34445,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "900w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 8,
            "Weight (lb)": 41,
            "Width (in)": 20.7,
            "Height (in)": 24.6,
            "Depth (in)": 17.4,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Senior 900w LED (Tungsten)(Maximum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 6400,
            "Lux @ 5’ (Tungsten)": 68890,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "900w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 8,
            "Weight (lb)": 41,
            "Width (in)": 20.7,
            "Height (in)": 24.6,
            "Depth (in)": 17.4,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Studio Junior 400w Bi-Color LED(Minimum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": "2700-6500",
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 1200,
            "Lux @ 5’ (Tungsten)": 12917,
            "FC @ 5’ (Daylight)": 1300,
            "Lux @ 5’ ": 13993,
            "Spot Diameter @ 5'": 4.5,
            "Lumens": null,
            "Watts": "400w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 4,
            "Weight (lb)": 27.5,
            "Width (in)": 16.6,
            "Height (in)": 21.3,
            "Depth (in)": 17.25,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX- WxDMX- BT",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Studio Junior 400w Bi-Color LED(Maximum)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": "2700-6500",
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": 3000,
            "Lux @ 5’ (Tungsten)": 32292,
            "FC @ 5’ (Daylight)": 3100,
            "Lux @ 5’ ": 33368,
            "Spot Diameter @ 5'": 1.5,
            "Lumens": null,
            "Watts": "400w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 4,
            "Weight (lb)": 27.5,
            "Width (in)": 16.6,
            "Height (in)": 21.3,
            "Depth (in)": 17.25,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX- WxDMX- BT",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Tener 1600w LED (Daylight)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": 5600,
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": "8000-16000",
            "Lux @ 5’ ": "86112-172224",
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "1600w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 90,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 14.5,
            "Weight (lb)": 70,
            "Width (in)": 24.4,
            "Height (in)": 32.9,
            "Depth (in)": 23.2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Mole",
            "Model": "Tener 1600w LED (Tungsten)",
            "Type": "LED",
            "Style": "Fresnel",
            "Color Temp": 3200,
            "Beam Angle": "10-55",
            "FC @ 5’ (Tungsten)        .": "6400-12800",
            "Lux @ 5’ (Tungsten)": "68890-137779",
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": null,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "1600w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": 95,
            "TLCI": null,
            "Voltage": "90-250",
            "Amps": 14.5,
            "Weight (lb)": 70,
            "Width (in)": 24.4,
            "Height (in)": 32.9,
            "Depth (in)": 23.2,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": "DMX",
            "Notes": null,
            "Data Reference": "http://mole.com/media/images/catalogs/pdfs/moleled/MoleLED_Brochure.pdf"
          },
          {
            "Brand": "Quasar",
            "Model": "Q-LED R Rainbow",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "RGBW",
            "Beam Angle": null,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": 0,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": 0,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": null,
            "Battery plate available?": null,
            "Dimmable": null,
            "CRI": null,
            "TLCI": null,
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": null,
            "Width (in)": null,
            "Height (in)": null,
            "Depth (in)": null,
            "Flicker Free?": null,
            "Ballast / Dimmer": null,
            "Remote Control": null,
            "Notes": null,
            "Data Reference": null
          },
          {
            "Brand": "Quasar",
            "Model": "Q-LED X Crossfade 1'",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "2000-6000",
            "Beam Angle": 180,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": 0,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": 0,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "15w",
            "Battery plate available?": null,
            "Dimmable": null,
            "CRI": "95+",
            "TLCI": "97+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": null,
            "Width (in)": null,
            "Height (in)": null,
            "Depth (in)": null,
            "Flicker Free?": null,
            "Ballast / Dimmer": "Integrated",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": null
          },
          {
            "Brand": "Quasar",
            "Model": " Q-LED X Crossfade 2' ",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "2000-6000",
            "Beam Angle": 180,
            "FC @ 5’ (Tungsten)        .": 13,
            "Lux @ 5’ (Tungsten)": 139.932,
            "FC @ 5’ (Daylight)": 24,
            "Lux @ 5’ ": 258.336,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "25w",
            "Battery plate available?": null,
            "Dimmable": null,
            "CRI": "95+",
            "TLCI": "97+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": null,
            "Width (in)": null,
            "Height (in)": null,
            "Depth (in)": null,
            "Flicker Free?": null,
            "Ballast / Dimmer": "Integrated",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": null
          },
          {
            "Brand": "Quasar",
            "Model": "Q-LED X Crossfade 4'",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "2000-6000",
            "Beam Angle": 180,
            "FC @ 5’ (Tungsten)        .": 28,
            "Lux @ 5’ (Tungsten)": 301.392,
            "FC @ 5’ (Daylight)": 52,
            "Lux @ 5’ ": 559.728,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "50w",
            "Battery plate available?": null,
            "Dimmable": null,
            "CRI": "95+",
            "TLCI": "97+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": null,
            "Width (in)": null,
            "Height (in)": null,
            "Depth (in)": null,
            "Flicker Free?": null,
            "Ballast / Dimmer": "Integrated",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": null
          },
          {
            "Brand": "Quasar",
            "Model": " Q-LED X Crossfade 6'",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "2000-6000",
            "Beam Angle": 180,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": 0,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": 0,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "75w",
            "Battery plate available?": null,
            "Dimmable": null,
            "CRI": "95+",
            "TLCI": "97+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": null,
            "Width (in)": null,
            "Height (in)": null,
            "Depth (in)": null,
            "Flicker Free?": null,
            "Ballast / Dimmer": "Integrated",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": null
          },
          {
            "Brand": "Quasar",
            "Model": "Q-LED X Crossfade 8'",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": "2000-6000",
            "Beam Angle": 180,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": 0,
            "FC @ 5’ (Daylight)": null,
            "Lux @ 5’ ": 0,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "100w",
            "Battery plate available?": null,
            "Dimmable": null,
            "CRI": "95+",
            "TLCI": "97+",
            "Voltage": null,
            "Amps": null,
            "Weight (lb)": null,
            "Width (in)": null,
            "Height (in)": null,
            "Depth (in)": null,
            "Flicker Free?": null,
            "Ballast / Dimmer": "Integrated",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": null
          },
          {
            "Brand": "Westcott",
            "Model": " Flex 1' x 1' ",
            "Type": "LED",
            "Style": "Flex Panel",
            "Color Temp": "2800-6000",
            "Beam Angle": "140-360",
            "FC @ 5’ (Tungsten)        .": 104,
            "Lux @ 5’ (Tungsten)": 1119.456,
            "FC @ 5’ (Daylight)": 120,
            "Lux @ 5’ ": 1291.6799999999998,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "55w",
            "Battery plate available?": "yes",
            "Dimmable": "Dimmable",
            "CRI": "95-98",
            "TLCI": "97-98",
            "Voltage": "110-220",
            "Amps": null,
            "Weight (lb)": 4,
            "Width (in)": 12.1,
            "Height (in)": 12.1,
            "Depth (in)": 0.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.fjwestcott.com/flex-1x1-led-mat"
          },
          {
            "Brand": "Westcott",
            "Model": "Flex 1' x 2' ",
            "Type": "LED",
            "Style": "Flex Panel",
            "Color Temp": "2800-6000",
            "Beam Angle": "140-360",
            "FC @ 5’ (Tungsten)        .": 197,
            "Lux @ 5’ (Tungsten)": 2120.508,
            "FC @ 5’ (Daylight)": 220,
            "Lux @ 5’ ": 2368.08,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "100w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": "95-98",
            "TLCI": "97-98",
            "Voltage": "110-221",
            "Amps": null,
            "Weight (lb)": 5.7,
            "Width (in)": 23.9,
            "Height (in)": 12.1,
            "Depth (in)": 0.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.fjwestcott.com/flex-1x2-led-mat"
          },
          {
            "Brand": "Westcott",
            "Model": "Flex 1' x 3' ",
            "Type": "LED",
            "Style": "Flex Panel",
            "Color Temp": "2800-6000",
            "Beam Angle": "140-360",
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 379,
            "Lux @ 5’ ": 4079.5559999999996,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "150w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": "95-98",
            "TLCI": "97-98",
            "Voltage": "110-222",
            "Amps": null,
            "Weight (lb)": 11,
            "Width (in)": 38,
            "Height (in)": 12.1,
            "Depth (in)": 0.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.fjwestcott.com/flex-1-x-3-daylight-mat"
          },
          {
            "Brand": "Westcott",
            "Model": "Flex 2' x 2' ",
            "Type": "LED",
            "Style": "Flex Panel",
            "Color Temp": "2800-6000",
            "Beam Angle": "140-360",
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 541,
            "Lux @ 5’ ": 5823.324,
            "Spot Diameter @ 5'": null,
            "Lumens": null,
            "Watts": "200w",
            "Battery plate available?": "no",
            "Dimmable": "Dimmable",
            "CRI": "95-98",
            "TLCI": "97-98",
            "Voltage": "110-223",
            "Amps": null,
            "Weight (lb)": 14.6,
            "Width (in)": 23.9,
            "Height (in)": 23.9,
            "Depth (in)": 0.3,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Off Unit",
            "Remote Control": null,
            "Notes": null,
            "Data Reference": "https://www.fjwestcott.com/flex-2-x-2-daylight-mat"
          },
          {
            "Brand": "Westcott",
            "Model": "Icelight 2",
            "Type": "LED",
            "Style": "Tube",
            "Color Temp": 5500,
            "Beam Angle": 72.6,
            "FC @ 5’ (Tungsten)        .": null,
            "Lux @ 5’ (Tungsten)": null,
            "FC @ 5’ (Daylight)": 28,
            "Lux @ 5’ ": 301.392,
            "Spot Diameter @ 5'": null,
            "Lumens": 1740,
            "Watts": "19w",
            "Battery plate available?": "integrated / removable",
            "Dimmable": "10-step",
            "CRI": 97,
            "TLCI": 97,
            "Voltage": "100-240",
            "Amps": null,
            "Weight (lb)": 1.25,
            "Width (in)": 21.6,
            "Height (in)": 1.7,
            "Depth (in)": 1.7,
            "Flicker Free?": "Flicker Free",
            "Ballast / Dimmer": "Integrated",
            "Remote Control": "BT",
            "Notes": null,
            "Data Reference": "https://www.fjwestcott.com/ice-light-2"
          }
        ]
      }